### ISSUE TITLE
Does the 2.1 version of the program add image enhancement?

### ISSUE THREAD

**Issue by ma3252788** [JialeCao001/D2Det-mmdet2.1#3]
The same data set, using the 1.1 version of the program, the training speed is very fast, but using the 2.1 version of the program, the speed is very slow.
![image](https://user-images.githubusercontent.com/22229456/94165844-3afaa400-febd-11ea-9f49-117cc3c07fb4.png)
![image](https://user-images.githubusercontent.com/22229456/94165895-477efc80-febd-11ea-810c-1b5ed075576b.png)

I wonder if there are many new enhancements to the data in 2.1?

**Comment by ma3252788** [comment]
The result came out today. Comparing the two versions with the same data set, the mAP value of version 2.1 is 5% lower than the mAP value of version 1.1

**Comment by JialeCao001** [comment]
Is the result on MS COCO?

**Comment by ma3252788** [comment]
> Is the result on MS COCO?

NO, it's a self-built data set of mine.

**Comment by JialeCao001** [comment]
@ma3252788 I am not sure about the problem. I think these two versions do not use image enhancement. From the information you provide, it seems the batch size is not same?

**Comment by QY1994-0919** [comment]
> > Is the result on MS COCO?
> 
> NO, it's a self-built data set of mine.



> The same data set, using the 1.1 version of the program, the training speed is very fast, but using the 2.1 version of the program, the speed is very slow.
> ![image](https://user-images.githubusercontent.com/22229456/94165844-3afaa400-febd-11ea-9f49-117cc3c07fb4.png)
> ![image](https://user-images.githubusercontent.com/22229456/94165895-477efc80-febd-11ea-810c-1b5ed075576b.png)
> 
> I wonder if there are many new enhancements to the data in 2.1?

Hello，When I am doing demo.py testing , I always get this error. So I want to ask you for some advice

which: no nvcc in (/home/10102010/qy/mm2.3envir/anaconda3/cd../envs/mmd21/bin:/cm/shared/apps/gcc5/5.5.0/bin:/cm/shared/apps/slurm/current/sbin:/cm/shared/apps/slurm/current/bin:/cm/local/apps/environment-modules/4.4.0//bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/sbin:/cm/local/apps/environment-modules/4.4.0/bin:/home/10102010/.local/bin:/home/10102010/bin)
The model and loaded state dict do not match exactly

unexpected key in source state_dict: bbox_roi_extractor.roi_layers.0.awp.weight.conv.weight, bbox_roi_extractor.roi_layers.0.awp.weight.bn.weight, bbox_roi_extractor.roi_layers.0.awp.weight.bn.bias, bbox_roi_extractor.roi_layers.0.offset_fc.0.weight, bbox_roi_extractor.roi_layers.0.offset_fc.0.bias, bbox_roi_extractor.roi_layers.0.offset_fc.2.weight, bbox_roi_extractor.roi_layers.0.offset_fc.2.bias, bbox_roi_extractor.roi_layers.0.offset_fc.4.weight, bbox_roi_extractor.roi_layers.0.offset_fc.4.bias, bbox_roi_extractor.roi_layers.1.awp.weight.conv.weight, bbox_roi_extractor.roi_layers.1.awp.weight.bn.weight, bbox_roi_extractor.roi_layers.1.awp.weight.bn.bias, bbox_roi_extractor.roi_layers.1.offset_fc.0.weight, bbox_roi_extractor.roi_layers.1.offset_fc.0.bias, bbox_roi_extractor.roi_layers.1.offset_fc.2.weight, bbox_roi_extractor.roi_layers.1.offset_fc.2.bias, bbox_roi_extractor.roi_layers.1.offset_fc.4.weight, bbox_roi_extractor.roi_layers.1.offset_fc.4.bias, bbox_roi_extractor.roi_layers.2.awp.weight.conv.weight, bbox_roi_extractor.roi_layers.2.awp.weight.bn.weight, bbox_roi_extractor.roi_layers.2.awp.weight.bn.bias, bbox_roi_extractor.roi_layers.2.offset_fc.0.weight, bbox_roi_extractor.roi_layers.2.offset_fc.0.bias, bbox_roi_extractor.roi_layers.2.offset_fc.2.weight, bbox_roi_extractor.roi_layers.2.offset_fc.2.bias, bbox_roi_extractor.roi_layers.2.offset_fc.4.weight, bbox_roi_extractor.roi_layers.2.offset_fc.4.bias, bbox_roi_extractor.roi_layers.3.awp.weight.conv.weight, bbox_roi_extractor.roi_layers.3.awp.weight.bn.weight, bbox_roi_extractor.roi_layers.3.awp.weight.bn.bias, bbox_roi_extractor.roi_layers.3.offset_fc.0.weight, bbox_roi_extractor.roi_layers.3.offset_fc.0.bias, bbox_roi_extractor.roi_layers.3.offset_fc.2.weight, bbox_roi_extractor.roi_layers.3.offset_fc.2.bias, bbox_roi_extractor.roi_layers.3.offset_fc.4.weight, bbox_roi_extractor.roi_layers.3.offset_fc.4.bias, bbox_head.fc_cls.weight, bbox_head.fc_cls.bias, bbox_head.shared_fcs.0.weight, bbox_head.shared_fcs.0.bias, bbox_head.shared_fcs.1.weight, bbox_head.shared_fcs.1.bias, D2Det_head.convs.0.conv.weight, D2Det_head.convs.0.gn.weight, D2Det_head.convs.0.gn.bias, D2Det_head.convs.1.conv.weight, D2Det_head.convs.1.gn.weight, D2Det_head.convs.1.gn.bias, D2Det_head.convs.2.conv.weight, D2Det_head.convs.2.gn.weight, D2Det_head.convs.2.gn.bias, D2Det_head.convs.3.conv.weight, D2Det_head.convs.3.gn.weight, D2Det_head.convs.3.gn.bias, D2Det_head.convs.4.conv.weight, D2Det_head.convs.4.gn.weight, D2Det_head.convs.4.gn.bias, D2Det_head.convs.5.conv.weight, D2Det_head.convs.5.gn.weight, D2Det_head.convs.5.gn.bias, D2Det_head.convs.6.conv.weight, D2Det_head.convs.6.gn.weight, D2Det_head.convs.6.gn.bias, D2Det_head.convs.7.conv.weight, D2Det_head.convs.7.gn.weight, D2Det_head.convs.7.gn.bias, D2Det_head.D2Det_reg.weight, D2Det_head.D2Det_reg.bias, D2Det_head.D2Det_mask.weight, D2Det_head.D2Det_mask.bias, D2Det_head.deconv1.weight, D2Det_head.deconv1.bias, D2Det_head.norm1.weight, D2Det_head.norm1.bias, D2Det_head.deconv2.weight, D2Det_head.deconv2.bias, D2Det_head.D2Det_instance.weight, D2Det_head.D2Det_instance.bias, D2Det_head.fcs.0.weight, D2Det_head.fcs.0.bias, D2Det_head.fcs.1.weight, D2Det_head.fcs.1.bias, D2Det_head.fc_instance_iou.weight, D2Det_head.fc_instance_iou.bias

missing keys in source state_dict: roi_head.bbox_roi_extractor.roi_layers.0.awp.weight.conv.weight, roi_head.bbox_roi_extractor.roi_layers.0.awp.weight.bn.weight, roi_head.bbox_roi_extractor.roi_layers.0.awp.weight.bn.bias, roi_head.bbox_roi_extractor.roi_layers.0.offset_fc.0.weight, roi_head.bbox_roi_extractor.roi_layers.0.offset_fc.0.bias, roi_head.bbox_roi_extractor.roi_layers.0.offset_fc.2.weight, roi_head.bbox_roi_extractor.roi_layers.0.offset_fc.2.bias, roi_head.bbox_roi_extractor.roi_layers.0.offset_fc.4.weight, roi_head.bbox_roi_extractor.roi_layers.0.offset_fc.4.bias, roi_head.bbox_roi_extractor.roi_layers.1.awp.weight.conv.weight, roi_head.bbox_roi_extractor.roi_layers.1.awp.weight.bn.weight, roi_head.bbox_roi_extractor.roi_layers.1.awp.weight.bn.bias, roi_head.bbox_roi_extractor.roi_layers.1.offset_fc.0.weight, roi_head.bbox_roi_extractor.roi_layers.1.offset_fc.0.bias, roi_head.bbox_roi_extractor.roi_layers.1.offset_fc.2.weight, roi_head.bbox_roi_extractor.roi_layers.1.offset_fc.2.bias, roi_head.bbox_roi_extractor.roi_layers.1.offset_fc.4.weight, roi_head.bbox_roi_extractor.roi_layers.1.offset_fc.4.bias, roi_head.bbox_roi_extractor.roi_layers.2.awp.weight.conv.weight, roi_head.bbox_roi_extractor.roi_layers.2.awp.weight.bn.weight, roi_head.bbox_roi_extractor.roi_layers.2.awp.weight.bn.bias, roi_head.bbox_roi_extractor.roi_layers.2.offset_fc.0.weight, roi_head.bbox_roi_extractor.roi_layers.2.offset_fc.0.bias, roi_head.bbox_roi_extractor.roi_layers.2.offset_fc.2.weight, roi_head.bbox_roi_extractor.roi_layers.2.offset_fc.2.bias, roi_head.bbox_roi_extractor.roi_layers.2.offset_fc.4.weight, roi_head.bbox_roi_extractor.roi_layers.2.offset_fc.4.bias, roi_head.bbox_roi_extractor.roi_layers.3.awp.weight.conv.weight, roi_head.bbox_roi_extractor.roi_layers.3.awp.weight.bn.weight, roi_head.bbox_roi_extractor.roi_layers.3.awp.weight.bn.bias, roi_head.bbox_roi_extractor.roi_layers.3.offset_fc.0.weight, roi_head.bbox_roi_extractor.roi_layers.3.offset_fc.0.bias, roi_head.bbox_roi_extractor.roi_layers.3.offset_fc.2.weight, roi_head.bbox_roi_extractor.roi_layers.3.offset_fc.2.bias, roi_head.bbox_roi_extractor.roi_layers.3.offset_fc.4.weight, roi_head.bbox_roi_extractor.roi_layers.3.offset_fc.4.bias, roi_head.bbox_head.fc_cls.weight, roi_head.bbox_head.fc_cls.bias, roi_head.bbox_head.shared_fcs.0.weight, roi_head.bbox_head.shared_fcs.0.bias, roi_head.bbox_head.shared_fcs.1.weight, roi_head.bbox_head.shared_fcs.1.bias, roi_head.D2Det_head.convs.0.conv.weight, roi_head.D2Det_head.convs.0.gn.weight, roi_head.D2Det_head.convs.0.gn.bias, roi_head.D2Det_head.D2Det_reg.weight, roi_head.D2Det_head.D2Det_reg.bias, roi_head.D2Det_head.D2Det_mask.weight, roi_head.D2Det_head.D2Det_mask.bias, roi_head.D2Det_head.deconv1.weight, roi_head.D2Det_head.deconv1.bias, roi_head.D2Det_head.norm1.weight, roi_head.D2Det_head.norm1.bias, roi_head.D2Det_head.deconv2.weight, roi_head.D2Det_head.deconv2.bias, roi_head.D2Det_head.D2Det_instance.weight, roi_head.D2Det_head.D2Det_instance.bias, roi_head.D2Det_head.fcs.0.weight, roi_head.D2Det_head.fcs.0.bias, roi_head.D2Det_head.fcs.1.weight, roi_head.D2Det_head.fcs.1.bias, roi_head.D2Det_head.fc_instance_iou.weight, roi_head.D2Det_head.fc_instance_iou.bias

Traceback (most recent call last):
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/demo/D2Det_demo.py", line 30, in <module>
    main()
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/demo/D2Det_demo.py", line 24, in main
    result = inference_detector(model, args.img_file)
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/demo/../mmdet/apis/inference.py", line 104, in inference_detector
    result = model(return_loss=False, rescale=True, **data)
  File "/home/10102010/qy/mm2.3envir/anaconda3/cd../envs/mmd21/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/demo/../mmdet/core/fp16/decorators.py", line 51, in new_func
    return old_func(*args, **kwargs)
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/demo/../mmdet/models/detectors/base.py", line 150, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/demo/../mmdet/models/detectors/base.py", line 131, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/demo/../mmdet/models/detectors/two_stage.py", line 187, in simple_test
    proposal_list = self.rpn_head.simple_test_rpn(x, img_metas)
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/demo/../mmdet/models/dense_heads/rpn_test_mixin.py", line 26, in simple_test_rpn
    proposal_list = self.get_bboxes(*rpn_outs, img_metas)
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/demo/../mmdet/core/fp16/decorators.py", line 131, in new_func
    return old_func(*args, **kwargs)
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/demo/../mmdet/models/dense_heads/anchor_head.py", line 496, in get_bboxes
    scale_factor, cfg, rescale)
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/demo/../mmdet/models/dense_heads/rpn_head.py", line 120, in _get_bboxes_single
    dets, keep = batched_nms(proposals, scores, ids, nms_cfg)
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/demo/../mmdet/ops/nms/nms_wrapper.py", line 154, in batched_nms
    torch.cat([bboxes_for_nms, scores[:, None]], -1), **nms_cfg_)
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/demo/../mmdet/ops/nms/nms_wrapper.py", line 53, in nms
    inds = nms_ext.nms(dets_th, iou_thr)
RuntimeError: nms is not compiled with GPU support (nms at mmdet/ops/nms/src/nms_ext.cpp:23)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x2aaaf6bad627 in /home/10102010/qy/mm2.3envir/anaconda3/cd../envs/mmd21/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: nms(at::Tensor const&, float) + 0xfd (0x2aab11f952cd in /home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/demo/../mmdet/ops/nms/nms_ext.cpython-36m-x86_64-linux-gnu.so)
frame #2: <unknown function> + 0x192a5 (0x2aab11fa12a5 in /home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/demo/../mmdet/ops/nms/nms_ext.cpython-36m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x15796 (0x2aab11f9d796 in /home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/demo/../mmdet/ops/nms/nms_ext.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
